spring.cassandra.contact-points=localhost
server.port=24130
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=distcomp
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS